sudo: false
language: node_js
node_js:
  - '0.10'
  - '0.12'
before_install:
  - 'npm install -g npm@latest'
  - 'npm install electron-prebuilt' # seemed weird to have it a devDep
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
script: 'npm run ci'
