'use strict';

const constants = {
  UPDATE_CONTENT: 'UPDATE_CONTENT',
  UPDATE_FILENAME: 'UPDATE_FILENAME',
  ERROR: 'ERROR',
  NEW_FILE: 'NEW_FILE',
  SAVE_FILE: 'SAVE_FILE',
  DELETE_FILE: 'DELETE_FILE',
  CHANGE_FILE: 'CHANGE_FILE',
  DELETE_DIRECTORY: 'DELETE_DIRECTORY',
  CHANGE_DIRECTORY: 'CHANGE_DIRECTORY',
  REFRESH_DIRECTORY: 'REFRESH_DIRECTORY'
};

module.exports = constants;
